snack-25/front

- commitlint.config.js
> 🐛 fix(commitlint): commitlint 규칙 완화

- .lintstagedrc.js
- commitlint.config.js
- package.json
- pnpm-lock.yaml
- stylelint.config.mjs
> ⬆️ chore(deps): TailwindCSS 버전 업데이트(4.0.9 -> 4.0.10)

- src/app/playground/page.tsx
- tailwind.config.ts
- 임의로 확인할 디렉토리(playground) 만들었습니다
> feat:브레이크 포인트 설정

- package.json
- pnpm-lock.yaml
- src/app/globals.css
- src/app/modal-test/page.tsx
> [FE] 입력폼 없는 모달 UI 구현

- src/app/modal-test/page.tsx
- src/components/ui/TextArea.tsx
- src/components/ui/modal/BaseFormModal.tsx
- src/components/ui/modal/Modal.tsx
> ✨ feat(common-components): base form modal component

- src/app/layout.tsx
- Header 컴포넌트 RootLayOut Body태그에 삽입
> ✨ feat(Header): add Header to RootLayOut

- src/app/layout.tsx
- src/app/productList/page.tsx
- src/components/gnb/Header.tsx
- src/components/gnb/TabMenu.tsx
- src/components/ui/button.tsx
- gnb/
- TabMenu Component 구현 완료
- 공통 Header Component 수정
- 유저타입 수정(string -> union)
- border-bottom 추가
- 페이지 위치에 따른 헤더 버튼 요소 컬러 처리 
- 공통 레이아웃(RootLayOut)
- bg-background-400 추가
> ✨ feat(ProductList): add gnb/TabMenu Component

- src/app/modal-test/page.tsx
- src/components/ui/modal/MemberRoleChangeModal.tsx
> [FE} ✨ feat(common-components): 회원 권한 변경 모달

- src/app/modal-test/page.tsx
- src/components/ui/modal/PurchaseRequestModal.tsx
- textArea 8자 미만 입력시 버튼 비활성화 구현
> [FE]🐛 fix(common-components): 구매요청 모달 버튼 비활성화 구현

- package.json
- src/app/globals.css
- src/app/productList/[id]/page.tsx
- src/app/productList/page.tsx
- src/components/productList/FloatingButton.tsx
- src/components/productList/ProductCard.tsx
- src/components/productList/SortDropDown.tsx
- 상품 등록 FloatingButton 컴포넌트 구현
- globals.css에 illustration-06 컬러 추가
- 일부 컴포넌트 컬러 수정
- package.json 에서 packageManager 제거
- sortDropDown 중복 텍스트 제거
> ✨ feat(ProductList): FloatingButton 상품 등록 플로팅 버튼 추가

- src/app/productList/page.tsx
- src/components/productList/MoreButton.tsx
더보기 버튼 컴포넌트 구현하였습니다
기능은 아직 추가하지 않았습니다
> ✨ feat(ProductList): 더보기 버튼 컴포넌트 추가

- src/app/not-found.tsx
- src/app/productList/[id]/page.tsx
- src/app/productList/layout.tsx
- src/app/productList/page.tsx
- src/components/gnb/Header.tsx
- src/components/gnb/TabMenu.tsx
- src/components/productList/EmptyImage.tsx
- src/components/productList/ProductCard.tsx
- src/components/productList/ProductProvider.tsx
- src/components/productList/SortDropDown.tsx
- src/hooks/product/useFetchProduct.tsx
- notFound 페이지 추가
- 카테고리, 정렬 Context API를 이용하여 전역 상태 관리
- 상품 목록에서 상품 이미지 hover시에 shadow 처리
- 상품 상세 페이지에서 모달 관련 작업은 아직 이루어지지 않았습니다
> 상품 상세 페이지 api 연동 완료

- src/app/api/instance.ts
- src/hooks/product/useProductDelete.tsx
- src/lib/constants.ts
- `fetchApi`, `useProductDelete`, `constants`에서 API_BASE_URL을 환경변수로 통일하여 코드 일관성 향상
> 🐛 fix(api): API_BASE_URL 환경변수 통일

- public/icon/flat/X.svg
- src/app/auth/useAuthStore.ts
- src/app/cart/[cartId]/page.tsx
- src/components/cartItems/cartItem.tsx
- src/components/gnb/Header.tsx
- src/lib/api/cart.ts
- src/types/cart.ts
> 🎉 feature/장바구니페이지

- src/app/cart/[cartId]/page.tsx
> 🐛 fix:배포에러해결

- src/app/auth/login/page.tsx
- src/middleware.ts
> ✨ feat: 로그인 페이지 및 미들웨어에서 인증 로직 개선

- src/app/auth/login/page.tsx
- src/app/management/layout.tsx
- src/app/management/users/page.tsx
management 폴더에 layout.tsx추가하여 네비게이션 추가
> Feat/페이지작업/회원가입/최고관리자 회원가입

- src/app/history/components/SummaryCards.tsx
> 🐛 fix(history): 예산 에러 수정

- src/middleware.ts
> 🐛 fix : 미들웨어 경로 추가

- src/app/management/users/page.tsx
- src/components/ui/modal/InviteMemberModal.tsx
- src/types/user.ts
> [front ]Feature/management member only list

- src/components/orderRequestDetail/OrderRequestInfo.tsx
- src/types/cart.ts
> 🐛 fix : 구매요청완료페이지 수정

- src/components/orderRequestDetail/OrderRequestInfo.tsx
> 🐛 fix : 구매요청페이지 수정
